/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EoiRequestId = IDL.Nat;
export const MemberId = IDL.Nat;
export const PlanId = IDL.Nat;
export const EligibilityCheckResult = IDL.Record({
  'eligible' : IDL.Bool,
  'reason' : IDL.Text,
});
export const AssignmentRole = IDL.Variant({
  'admin' : IDL.Null,
  'billing' : IDL.Null,
  'underwriter' : IDL.Null,
  'viewer' : IDL.Null,
});
export const EnrollmentId = IDL.Nat;
export const BillingType = IDL.Variant({
  'list' : IDL.Null,
  'self' : IDL.Null,
  'retro' : IDL.Null,
});
export const BillingRecordId = IDL.Nat;
export const ClaimStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'validated' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const ClaimId = IDL.Nat;
export const DynamicEligibilityRule = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'planId' : PlanId,
  'name' : IDL.Text,
  'conditionsJson' : IDL.Text,
});
export const EmploymentType = IDL.Variant({
  'contract' : IDL.Null,
  'part_time' : IDL.Null,
  'full_time' : IDL.Null,
});
export const EligibilityRule = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'planId' : PlanId,
  'waitingPeriodDays' : IDL.Nat,
  'allowedEmploymentTypes' : IDL.Vec(EmploymentType),
});
export const EmployerId = IDL.Nat;
export const MemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'terminated' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : MemberId,
  'status' : MemberStatus,
  'salary' : IDL.Float64,
  'hireDateText' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : EmploymentType,
  'employerId' : EmployerId,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const PlanStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const CoverageType = IDL.Variant({
  'salary_multiple' : IDL.Null,
  'flat' : IDL.Null,
});
export const InsurancePlan = IDL.Record({
  'id' : PlanId,
  'status' : PlanStatus,
  'coverageValue' : IDL.Float64,
  'name' : IDL.Text,
  'effectiveDateText' : IDL.Text,
  'version' : IDL.Nat,
  'giLimit' : IDL.Float64,
  'coverageType' : CoverageType,
});
export const AssignmentId = IDL.Nat;
export const EligibilityEvalResult = IDL.Record({
  'matchedRuleId' : IDL.Opt(IDL.Nat),
  'eligible' : IDL.Bool,
  'reason' : IDL.Text,
});
export const AssignmentStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'status' : AssignmentStatus,
  'name' : IDL.Text,
  'role' : AssignmentRole,
  'email' : IDL.Text,
});
export const BillingStatus = IDL.Variant({
  'paid' : IDL.Null,
  'issued' : IDL.Null,
  'draft' : IDL.Null,
});
export const BillingRecord = IDL.Record({
  'id' : BillingRecordId,
  'status' : BillingStatus,
  'memberId' : MemberId,
  'enrollmentId' : EnrollmentId,
  'premium' : IDL.Float64,
  'rate' : IDL.Float64,
  'createdAtText' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'billingPeriodText' : IDL.Text,
  'coverageAmount' : IDL.Float64,
  'retroAdjustment' : IDL.Opt(IDL.Float64),
  'billingType' : BillingType,
});
export const Claim = IDL.Record({
  'id' : ClaimId,
  'status' : ClaimStatus,
  'memberId' : MemberId,
  'claimAmount' : IDL.Float64,
  'enrollmentId' : EnrollmentId,
  'coverageValid' : IDL.Bool,
  'coverageAmount' : IDL.Float64,
  'dateOfLossText' : IDL.Text,
});
export const EmployerStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Employer = IDL.Record({
  'id' : EmployerId,
  'status' : EmployerStatus,
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
  'industry' : IDL.Text,
});
export const EnrollmentStatus = IDL.Variant({
  'active' : IDL.Null,
  'terminated' : IDL.Null,
  'eoi_pending' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'id' : EnrollmentId,
  'status' : EnrollmentStatus,
  'memberId' : MemberId,
  'enrollmentDateText' : IDL.Text,
  'eoiTriggered' : IDL.Bool,
  'planId' : PlanId,
  'coverageAmount' : IDL.Float64,
});
export const EoiStatus = IDL.Variant({
  'pending' : IDL.Null,
  'in_review' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const AuditEntry = IDL.Record({
  'by' : IDL.Text,
  'action' : IDL.Text,
  'note' : IDL.Text,
  'atText' : IDL.Text,
});
export const EoiRequest = IDL.Record({
  'id' : EoiRequestId,
  'status' : EoiStatus,
  'memberId' : MemberId,
  'enrollmentId' : EnrollmentId,
  'assignedTo' : IDL.Opt(IDL.Text),
  'planId' : PlanId,
  'auditLog' : IDL.Vec(AuditEntry),
  'slaDeadlineText' : IDL.Text,
  'giLimit' : IDL.Float64,
  'coverageRequested' : IDL.Float64,
  'submittedAtText' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignEoiRequest' : IDL.Func(
      [EoiRequestId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'checkEligibility' : IDL.Func(
      [MemberId, PlanId],
      [EligibilityCheckResult],
      ['query'],
    ),
  'createAssignment' : IDL.Func([IDL.Text, IDL.Text, AssignmentRole], [], []),
  'createBillingRecord' : IDL.Func(
      [
        EnrollmentId,
        MemberId,
        BillingType,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [BillingRecordId],
      [],
    ),
  'createClaim' : IDL.Func(
      [
        MemberId,
        EnrollmentId,
        IDL.Text,
        IDL.Float64,
        ClaimStatus,
        IDL.Bool,
        IDL.Float64,
      ],
      [ClaimId],
      [],
    ),
  'createDynamicRule' : IDL.Func([DynamicEligibilityRule], [IDL.Nat], []),
  'createEligibilityRule' : IDL.Func([EligibilityRule], [], []),
  'createEmployer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [EmployerId], []),
  'createEoiRequest' : IDL.Func(
      [
        EnrollmentId,
        MemberId,
        PlanId,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createMember' : IDL.Func([Member], [MemberId], []),
  'createPlan' : IDL.Func([InsurancePlan], [PlanId], []),
  'deleteAssignment' : IDL.Func([AssignmentId], [], []),
  'deleteDynamicRule' : IDL.Func([IDL.Nat], [], []),
  'deleteEligibilityRule' : IDL.Func([IDL.Nat], [], []),
  'deleteEmployer' : IDL.Func([EmployerId], [], []),
  'deleteMember' : IDL.Func([MemberId], [], []),
  'deletePlan' : IDL.Func([PlanId], [], []),
  'enrollMember' : IDL.Func(
      [MemberId, PlanId, IDL.Float64, IDL.Text],
      [EnrollmentId],
      [],
    ),
  'evaluateMemberEligibility' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [EligibilityEvalResult],
      ['query'],
    ),
  'getActiveAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
  'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getAllDynamicRules' : IDL.Func(
      [],
      [IDL.Vec(DynamicEligibilityRule)],
      ['query'],
    ),
  'getAllEligibilityRules' : IDL.Func(
      [],
      [IDL.Vec(EligibilityRule)],
      ['query'],
    ),
  'getAllEmployers' : IDL.Func([], [IDL.Vec(Employer)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getAllEoiRequests' : IDL.Func([], [IDL.Vec(EoiRequest)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllPlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
  'getAssignmentsByRole' : IDL.Func(
      [AssignmentRole],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getBillingRecordsByMember' : IDL.Func(
      [MemberId],
      [IDL.Vec(BillingRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimsByMember' : IDL.Func([MemberId], [IDL.Vec(Claim)], ['query']),
  'getDynamicRulesByPlan' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DynamicEligibilityRule)],
      ['query'],
    ),
  'getEligibilityRule' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(EligibilityRule)],
      ['query'],
    ),
  'getEmployer' : IDL.Func([EmployerId], [IDL.Opt(Employer)], ['query']),
  'getEnrollmentsByMember' : IDL.Func(
      [MemberId],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getEoiRequestsByStatus' : IDL.Func(
      [EoiStatus],
      [IDL.Vec(EoiRequest)],
      ['query'],
    ),
  'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
  'getMembersByEmployer' : IDL.Func([EmployerId], [IDL.Vec(Member)], ['query']),
  'getPlan' : IDL.Func([PlanId], [IDL.Opt(InsurancePlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seed' : IDL.Func([], [], []),
  'updateAssignment' : IDL.Func([AssignmentId, Assignment], [], []),
  'updateBillingRecord' : IDL.Func([BillingRecordId, BillingRecord], [], []),
  'updateClaim' : IDL.Func([ClaimId, Claim], [], []),
  'updateDynamicRule' : IDL.Func([IDL.Nat, DynamicEligibilityRule], [], []),
  'updateEligibilityRule' : IDL.Func([IDL.Nat, EligibilityRule], [], []),
  'updateEmployer' : IDL.Func([EmployerId, Employer], [], []),
  'updateEoiStatus' : IDL.Func(
      [EoiRequestId, EoiStatus, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMember' : IDL.Func([MemberId, Member], [], []),
  'updatePlan' : IDL.Func([PlanId, InsurancePlan], [], []),
  'validateClaim' : IDL.Func(
      [MemberId, EnrollmentId],
      [IDL.Bool, IDL.Float64],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EoiRequestId = IDL.Nat;
  const MemberId = IDL.Nat;
  const PlanId = IDL.Nat;
  const EligibilityCheckResult = IDL.Record({
    'eligible' : IDL.Bool,
    'reason' : IDL.Text,
  });
  const AssignmentRole = IDL.Variant({
    'admin' : IDL.Null,
    'billing' : IDL.Null,
    'underwriter' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const EnrollmentId = IDL.Nat;
  const BillingType = IDL.Variant({
    'list' : IDL.Null,
    'self' : IDL.Null,
    'retro' : IDL.Null,
  });
  const BillingRecordId = IDL.Nat;
  const ClaimStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'validated' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const ClaimId = IDL.Nat;
  const DynamicEligibilityRule = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'planId' : PlanId,
    'name' : IDL.Text,
    'conditionsJson' : IDL.Text,
  });
  const EmploymentType = IDL.Variant({
    'contract' : IDL.Null,
    'part_time' : IDL.Null,
    'full_time' : IDL.Null,
  });
  const EligibilityRule = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'planId' : PlanId,
    'waitingPeriodDays' : IDL.Nat,
    'allowedEmploymentTypes' : IDL.Vec(EmploymentType),
  });
  const EmployerId = IDL.Nat;
  const MemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : MemberId,
    'status' : MemberStatus,
    'salary' : IDL.Float64,
    'hireDateText' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : EmploymentType,
    'employerId' : EmployerId,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const PlanStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const CoverageType = IDL.Variant({
    'salary_multiple' : IDL.Null,
    'flat' : IDL.Null,
  });
  const InsurancePlan = IDL.Record({
    'id' : PlanId,
    'status' : PlanStatus,
    'coverageValue' : IDL.Float64,
    'name' : IDL.Text,
    'effectiveDateText' : IDL.Text,
    'version' : IDL.Nat,
    'giLimit' : IDL.Float64,
    'coverageType' : CoverageType,
  });
  const AssignmentId = IDL.Nat;
  const EligibilityEvalResult = IDL.Record({
    'matchedRuleId' : IDL.Opt(IDL.Nat),
    'eligible' : IDL.Bool,
    'reason' : IDL.Text,
  });
  const AssignmentStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'status' : AssignmentStatus,
    'name' : IDL.Text,
    'role' : AssignmentRole,
    'email' : IDL.Text,
  });
  const BillingStatus = IDL.Variant({
    'paid' : IDL.Null,
    'issued' : IDL.Null,
    'draft' : IDL.Null,
  });
  const BillingRecord = IDL.Record({
    'id' : BillingRecordId,
    'status' : BillingStatus,
    'memberId' : MemberId,
    'enrollmentId' : EnrollmentId,
    'premium' : IDL.Float64,
    'rate' : IDL.Float64,
    'createdAtText' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'billingPeriodText' : IDL.Text,
    'coverageAmount' : IDL.Float64,
    'retroAdjustment' : IDL.Opt(IDL.Float64),
    'billingType' : BillingType,
  });
  const Claim = IDL.Record({
    'id' : ClaimId,
    'status' : ClaimStatus,
    'memberId' : MemberId,
    'claimAmount' : IDL.Float64,
    'enrollmentId' : EnrollmentId,
    'coverageValid' : IDL.Bool,
    'coverageAmount' : IDL.Float64,
    'dateOfLossText' : IDL.Text,
  });
  const EmployerStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Employer = IDL.Record({
    'id' : EmployerId,
    'status' : EmployerStatus,
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
    'industry' : IDL.Text,
  });
  const EnrollmentStatus = IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
    'eoi_pending' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'id' : EnrollmentId,
    'status' : EnrollmentStatus,
    'memberId' : MemberId,
    'enrollmentDateText' : IDL.Text,
    'eoiTriggered' : IDL.Bool,
    'planId' : PlanId,
    'coverageAmount' : IDL.Float64,
  });
  const EoiStatus = IDL.Variant({
    'pending' : IDL.Null,
    'in_review' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const AuditEntry = IDL.Record({
    'by' : IDL.Text,
    'action' : IDL.Text,
    'note' : IDL.Text,
    'atText' : IDL.Text,
  });
  const EoiRequest = IDL.Record({
    'id' : EoiRequestId,
    'status' : EoiStatus,
    'memberId' : MemberId,
    'enrollmentId' : EnrollmentId,
    'assignedTo' : IDL.Opt(IDL.Text),
    'planId' : PlanId,
    'auditLog' : IDL.Vec(AuditEntry),
    'slaDeadlineText' : IDL.Text,
    'giLimit' : IDL.Float64,
    'coverageRequested' : IDL.Float64,
    'submittedAtText' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignEoiRequest' : IDL.Func(
        [EoiRequestId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'checkEligibility' : IDL.Func(
        [MemberId, PlanId],
        [EligibilityCheckResult],
        ['query'],
      ),
    'createAssignment' : IDL.Func([IDL.Text, IDL.Text, AssignmentRole], [], []),
    'createBillingRecord' : IDL.Func(
        [
          EnrollmentId,
          MemberId,
          BillingType,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [BillingRecordId],
        [],
      ),
    'createClaim' : IDL.Func(
        [
          MemberId,
          EnrollmentId,
          IDL.Text,
          IDL.Float64,
          ClaimStatus,
          IDL.Bool,
          IDL.Float64,
        ],
        [ClaimId],
        [],
      ),
    'createDynamicRule' : IDL.Func([DynamicEligibilityRule], [IDL.Nat], []),
    'createEligibilityRule' : IDL.Func([EligibilityRule], [], []),
    'createEmployer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [EmployerId],
        [],
      ),
    'createEoiRequest' : IDL.Func(
        [
          EnrollmentId,
          MemberId,
          PlanId,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createMember' : IDL.Func([Member], [MemberId], []),
    'createPlan' : IDL.Func([InsurancePlan], [PlanId], []),
    'deleteAssignment' : IDL.Func([AssignmentId], [], []),
    'deleteDynamicRule' : IDL.Func([IDL.Nat], [], []),
    'deleteEligibilityRule' : IDL.Func([IDL.Nat], [], []),
    'deleteEmployer' : IDL.Func([EmployerId], [], []),
    'deleteMember' : IDL.Func([MemberId], [], []),
    'deletePlan' : IDL.Func([PlanId], [], []),
    'enrollMember' : IDL.Func(
        [MemberId, PlanId, IDL.Float64, IDL.Text],
        [EnrollmentId],
        [],
      ),
    'evaluateMemberEligibility' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [EligibilityEvalResult],
        ['query'],
      ),
    'getActiveAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
    'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getAllDynamicRules' : IDL.Func(
        [],
        [IDL.Vec(DynamicEligibilityRule)],
        ['query'],
      ),
    'getAllEligibilityRules' : IDL.Func(
        [],
        [IDL.Vec(EligibilityRule)],
        ['query'],
      ),
    'getAllEmployers' : IDL.Func([], [IDL.Vec(Employer)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getAllEoiRequests' : IDL.Func([], [IDL.Vec(EoiRequest)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllPlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
    'getAssignmentsByRole' : IDL.Func(
        [AssignmentRole],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getBillingRecordsByMember' : IDL.Func(
        [MemberId],
        [IDL.Vec(BillingRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimsByMember' : IDL.Func([MemberId], [IDL.Vec(Claim)], ['query']),
    'getDynamicRulesByPlan' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DynamicEligibilityRule)],
        ['query'],
      ),
    'getEligibilityRule' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EligibilityRule)],
        ['query'],
      ),
    'getEmployer' : IDL.Func([EmployerId], [IDL.Opt(Employer)], ['query']),
    'getEnrollmentsByMember' : IDL.Func(
        [MemberId],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getEoiRequestsByStatus' : IDL.Func(
        [EoiStatus],
        [IDL.Vec(EoiRequest)],
        ['query'],
      ),
    'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
    'getMembersByEmployer' : IDL.Func(
        [EmployerId],
        [IDL.Vec(Member)],
        ['query'],
      ),
    'getPlan' : IDL.Func([PlanId], [IDL.Opt(InsurancePlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seed' : IDL.Func([], [], []),
    'updateAssignment' : IDL.Func([AssignmentId, Assignment], [], []),
    'updateBillingRecord' : IDL.Func([BillingRecordId, BillingRecord], [], []),
    'updateClaim' : IDL.Func([ClaimId, Claim], [], []),
    'updateDynamicRule' : IDL.Func([IDL.Nat, DynamicEligibilityRule], [], []),
    'updateEligibilityRule' : IDL.Func([IDL.Nat, EligibilityRule], [], []),
    'updateEmployer' : IDL.Func([EmployerId, Employer], [], []),
    'updateEoiStatus' : IDL.Func(
        [EoiRequestId, EoiStatus, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMember' : IDL.Func([MemberId, Member], [], []),
    'updatePlan' : IDL.Func([PlanId, InsurancePlan], [], []),
    'validateClaim' : IDL.Func(
        [MemberId, EnrollmentId],
        [IDL.Bool, IDL.Float64],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };