/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : AssignmentId,
  'status' : AssignmentStatus,
  'name' : string,
  'role' : AssignmentRole,
  'email' : string,
}
export type AssignmentId = bigint;
export type AssignmentRole = { 'admin' : null } |
  { 'billing' : null } |
  { 'underwriter' : null } |
  { 'viewer' : null };
export type AssignmentStatus = { 'active' : null } |
  { 'inactive' : null };
export interface AuditEntry {
  'by' : string,
  'action' : string,
  'note' : string,
  'atText' : string,
}
export interface BillingRecord {
  'id' : BillingRecordId,
  'status' : BillingStatus,
  'memberId' : MemberId,
  'enrollmentId' : EnrollmentId,
  'premium' : number,
  'rate' : number,
  'createdAtText' : string,
  'invoiceNumber' : string,
  'billingPeriodText' : string,
  'coverageAmount' : number,
  'retroAdjustment' : [] | [number],
  'billingType' : BillingType,
}
export type BillingRecordId = bigint;
export type BillingStatus = { 'paid' : null } |
  { 'issued' : null } |
  { 'draft' : null };
export type BillingType = { 'list' : null } |
  { 'self' : null } |
  { 'retro' : null };
export interface Claim {
  'id' : ClaimId,
  'status' : ClaimStatus,
  'memberId' : MemberId,
  'claimAmount' : number,
  'enrollmentId' : EnrollmentId,
  'coverageValid' : boolean,
  'coverageAmount' : number,
  'dateOfLossText' : string,
}
export type ClaimId = bigint;
export type ClaimStatus = { 'submitted' : null } |
  { 'validated' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export type CoverageType = { 'salary_multiple' : null } |
  { 'flat' : null };
export interface DynamicEligibilityRule {
  'id' : bigint,
  'active' : boolean,
  'planId' : PlanId,
  'name' : string,
  'conditionsJson' : string,
}
export interface EligibilityCheckResult {
  'eligible' : boolean,
  'reason' : string,
}
export interface EligibilityEvalResult {
  'matchedRuleId' : [] | [bigint],
  'eligible' : boolean,
  'reason' : string,
}
export interface EligibilityRule {
  'id' : bigint,
  'active' : boolean,
  'planId' : PlanId,
  'waitingPeriodDays' : bigint,
  'allowedEmploymentTypes' : Array<EmploymentType>,
}
export interface Employer {
  'id' : EmployerId,
  'status' : EmployerStatus,
  'name' : string,
  'contactEmail' : string,
  'industry' : string,
}
export type EmployerId = bigint;
export type EmployerStatus = { 'active' : null } |
  { 'inactive' : null };
export type EmploymentType = { 'contract' : null } |
  { 'part_time' : null } |
  { 'full_time' : null };
export interface Enrollment {
  'id' : EnrollmentId,
  'status' : EnrollmentStatus,
  'memberId' : MemberId,
  'enrollmentDateText' : string,
  'eoiTriggered' : boolean,
  'planId' : PlanId,
  'coverageAmount' : number,
}
export type EnrollmentId = bigint;
export type EnrollmentStatus = { 'active' : null } |
  { 'terminated' : null } |
  { 'eoi_pending' : null };
export interface EoiRequest {
  'id' : EoiRequestId,
  'status' : EoiStatus,
  'memberId' : MemberId,
  'enrollmentId' : EnrollmentId,
  'assignedTo' : [] | [string],
  'planId' : PlanId,
  'auditLog' : Array<AuditEntry>,
  'slaDeadlineText' : string,
  'giLimit' : number,
  'coverageRequested' : number,
  'submittedAtText' : string,
}
export type EoiRequestId = bigint;
export type EoiStatus = { 'pending' : null } |
  { 'in_review' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface InsurancePlan {
  'id' : PlanId,
  'status' : PlanStatus,
  'coverageValue' : number,
  'name' : string,
  'effectiveDateText' : string,
  'version' : bigint,
  'giLimit' : number,
  'coverageType' : CoverageType,
}
export interface Member {
  'id' : MemberId,
  'status' : MemberStatus,
  'salary' : number,
  'hireDateText' : string,
  'email' : string,
  'employmentType' : EmploymentType,
  'employerId' : EmployerId,
  'lastName' : string,
  'firstName' : string,
}
export type MemberId = bigint;
export type MemberStatus = { 'active' : null } |
  { 'terminated' : null };
export type PlanId = bigint;
export type PlanStatus = { 'active' : null } |
  { 'inactive' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignEoiRequest' : ActorMethod<
    [EoiRequestId, string, string, string],
    undefined
  >,
  'checkEligibility' : ActorMethod<[MemberId, PlanId], EligibilityCheckResult>,
  'createAssignment' : ActorMethod<[string, string, AssignmentRole], undefined>,
  'createBillingRecord' : ActorMethod<
    [
      EnrollmentId,
      MemberId,
      BillingType,
      string,
      number,
      number,
      number,
      string,
      string,
    ],
    BillingRecordId
  >,
  'createClaim' : ActorMethod<
    [MemberId, EnrollmentId, string, number, ClaimStatus, boolean, number],
    ClaimId
  >,
  'createDynamicRule' : ActorMethod<[DynamicEligibilityRule], bigint>,
  'createEligibilityRule' : ActorMethod<[EligibilityRule], undefined>,
  'createEmployer' : ActorMethod<[string, string, string], EmployerId>,
  'createEoiRequest' : ActorMethod<
    [EnrollmentId, MemberId, PlanId, number, number, string, string],
    undefined
  >,
  'createMember' : ActorMethod<[Member], MemberId>,
  'createPlan' : ActorMethod<[InsurancePlan], PlanId>,
  'deleteAssignment' : ActorMethod<[AssignmentId], undefined>,
  'deleteDynamicRule' : ActorMethod<[bigint], undefined>,
  'deleteEligibilityRule' : ActorMethod<[bigint], undefined>,
  'deleteEmployer' : ActorMethod<[EmployerId], undefined>,
  'deleteMember' : ActorMethod<[MemberId], undefined>,
  'deletePlan' : ActorMethod<[PlanId], undefined>,
  'enrollMember' : ActorMethod<
    [MemberId, PlanId, number, string],
    EnrollmentId
  >,
  'evaluateMemberEligibility' : ActorMethod<
    [bigint, bigint],
    EligibilityEvalResult
  >,
  'getActiveAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllBillingRecords' : ActorMethod<[], Array<BillingRecord>>,
  'getAllClaims' : ActorMethod<[], Array<Claim>>,
  'getAllDynamicRules' : ActorMethod<[], Array<DynamicEligibilityRule>>,
  'getAllEligibilityRules' : ActorMethod<[], Array<EligibilityRule>>,
  'getAllEmployers' : ActorMethod<[], Array<Employer>>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getAllEoiRequests' : ActorMethod<[], Array<EoiRequest>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllPlans' : ActorMethod<[], Array<InsurancePlan>>,
  'getAssignmentsByRole' : ActorMethod<[AssignmentRole], Array<Assignment>>,
  'getBillingRecordsByMember' : ActorMethod<[MemberId], Array<BillingRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimsByMember' : ActorMethod<[MemberId], Array<Claim>>,
  'getDynamicRulesByPlan' : ActorMethod<
    [bigint],
    Array<DynamicEligibilityRule>
  >,
  'getEligibilityRule' : ActorMethod<[bigint], [] | [EligibilityRule]>,
  'getEmployer' : ActorMethod<[EmployerId], [] | [Employer]>,
  'getEnrollmentsByMember' : ActorMethod<[MemberId], Array<Enrollment>>,
  'getEoiRequestsByStatus' : ActorMethod<[EoiStatus], Array<EoiRequest>>,
  'getMember' : ActorMethod<[MemberId], [] | [Member]>,
  'getMembersByEmployer' : ActorMethod<[EmployerId], Array<Member>>,
  'getPlan' : ActorMethod<[PlanId], [] | [InsurancePlan]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seed' : ActorMethod<[], undefined>,
  'updateAssignment' : ActorMethod<[AssignmentId, Assignment], undefined>,
  'updateBillingRecord' : ActorMethod<
    [BillingRecordId, BillingRecord],
    undefined
  >,
  'updateClaim' : ActorMethod<[ClaimId, Claim], undefined>,
  'updateDynamicRule' : ActorMethod<
    [bigint, DynamicEligibilityRule],
    undefined
  >,
  'updateEligibilityRule' : ActorMethod<[bigint, EligibilityRule], undefined>,
  'updateEmployer' : ActorMethod<[EmployerId, Employer], undefined>,
  'updateEoiStatus' : ActorMethod<
    [EoiRequestId, EoiStatus, string, string, string],
    undefined
  >,
  'updateMember' : ActorMethod<[MemberId, Member], undefined>,
  'updatePlan' : ActorMethod<[PlanId, InsurancePlan], undefined>,
  'validateClaim' : ActorMethod<[MemberId, EnrollmentId], [boolean, number]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];