/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EoiRequestId = bigint;
export interface EligibilityEvalResult {
    matchedRuleId?: bigint;
    eligible: boolean;
    reason: string;
}
export type EmployerId = bigint;
export interface Enrollment {
    id: EnrollmentId;
    status: EnrollmentStatus;
    memberId: MemberId;
    enrollmentDateText: string;
    eoiTriggered: boolean;
    planId: PlanId;
    coverageAmount: number;
}
export interface Employer {
    id: EmployerId;
    status: EmployerStatus;
    name: string;
    contactEmail: string;
    industry: string;
}
export interface AuditEntry {
    by: string;
    action: string;
    note: string;
    atText: string;
}
export interface InsurancePlan {
    id: PlanId;
    status: PlanStatus;
    coverageValue: number;
    name: string;
    effectiveDateText: string;
    version: bigint;
    giLimit: number;
    coverageType: CoverageType;
}
export interface EligibilityRule {
    id: bigint;
    active: boolean;
    planId: PlanId;
    waitingPeriodDays: bigint;
    allowedEmploymentTypes: Array<EmploymentType>;
}
export type AssignmentId = bigint;
export interface Assignment {
    id: AssignmentId;
    status: AssignmentStatus;
    name: string;
    role: AssignmentRole;
    email: string;
}
export type PlanId = bigint;
export type ClaimId = bigint;
export type EnrollmentId = bigint;
export interface Claim {
    id: ClaimId;
    status: ClaimStatus;
    memberId: MemberId;
    claimAmount: number;
    enrollmentId: EnrollmentId;
    coverageValid: boolean;
    coverageAmount: number;
    dateOfLossText: string;
}
export interface EoiRequest {
    id: EoiRequestId;
    status: EoiStatus;
    memberId: MemberId;
    enrollmentId: EnrollmentId;
    assignedTo?: string;
    planId: PlanId;
    auditLog: Array<AuditEntry>;
    slaDeadlineText: string;
    giLimit: number;
    coverageRequested: number;
    submittedAtText: string;
}
export interface BillingRecord {
    id: BillingRecordId;
    status: BillingStatus;
    memberId: MemberId;
    enrollmentId: EnrollmentId;
    premium: number;
    rate: number;
    createdAtText: string;
    invoiceNumber: string;
    billingPeriodText: string;
    coverageAmount: number;
    retroAdjustment?: number;
    billingType: BillingType;
}
export type MemberId = bigint;
export interface DynamicEligibilityRule {
    id: bigint;
    active: boolean;
    planId: PlanId;
    name: string;
    conditionsJson: string;
}
export type BillingRecordId = bigint;
export interface Member {
    id: MemberId;
    status: MemberStatus;
    salary: number;
    hireDateText: string;
    email: string;
    employmentType: EmploymentType;
    employerId: EmployerId;
    lastName: string;
    firstName: string;
}
export interface EligibilityCheckResult {
    eligible: boolean;
    reason: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum AssignmentRole {
    admin = "admin",
    billing = "billing",
    underwriter = "underwriter",
    viewer = "viewer"
}
export enum BillingStatus {
    paid = "paid",
    issued = "issued",
    draft = "draft"
}
export enum BillingType {
    list = "list",
    self = "self",
    retro = "retro"
}
export enum ClaimStatus {
    submitted = "submitted",
    validated = "validated",
    denied = "denied",
    approved = "approved"
}
export enum CoverageType {
    salary_multiple = "salary_multiple",
    flat = "flat"
}
export enum EmployerStatus {
    active = "active",
    inactive = "inactive"
}
export enum EmploymentType {
    contract = "contract",
    part_time = "part_time",
    full_time = "full_time"
}
export enum EnrollmentStatus {
    active = "active",
    terminated = "terminated",
    eoi_pending = "eoi_pending"
}
export enum EoiStatus {
    pending = "pending",
    in_review = "in_review",
    approved = "approved",
    declined = "declined"
}
export enum MemberStatus {
    active = "active",
    terminated = "terminated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignEoiRequest(id: EoiRequestId, assignedTo: string, by: string, atText: string): Promise<void>;
    checkEligibility(memberId: MemberId, planId: PlanId): Promise<EligibilityCheckResult>;
    createAssignment(name: string, email: string, role: AssignmentRole): Promise<void>;
    createBillingRecord(enrollmentId: EnrollmentId, memberId: MemberId, billingType: BillingType, billingPeriodText: string, premium: number, rate: number, coverageAmount: number, invoiceNumber: string, createdAtText: string): Promise<BillingRecordId>;
    createClaim(memberId: MemberId, enrollmentId: EnrollmentId, dateOfLossText: string, claimAmount: number, status: ClaimStatus, coverageValid: boolean, coverageAmount: number): Promise<ClaimId>;
    createDynamicRule(rule: DynamicEligibilityRule): Promise<bigint>;
    createEligibilityRule(rule: EligibilityRule): Promise<void>;
    createEmployer(name: string, industry: string, contactEmail: string): Promise<EmployerId>;
    createEoiRequest(enrollmentId: EnrollmentId, memberId: MemberId, planId: PlanId, coverageRequested: number, giLimit: number, submittedAtText: string, slaDeadlineText: string): Promise<void>;
    createMember(member: Member): Promise<MemberId>;
    createPlan(plan: InsurancePlan): Promise<PlanId>;
    deleteAssignment(id: AssignmentId): Promise<void>;
    deleteDynamicRule(id: bigint): Promise<void>;
    deleteEligibilityRule(id: bigint): Promise<void>;
    deleteEmployer(id: EmployerId): Promise<void>;
    deleteMember(id: MemberId): Promise<void>;
    deletePlan(id: PlanId): Promise<void>;
    enrollMember(memberId: MemberId, planId: PlanId, coverageAmount: number, enrollmentDateText: string): Promise<EnrollmentId>;
    evaluateMemberEligibility(memberId: bigint, planId: bigint): Promise<EligibilityEvalResult>;
    getActiveAssignments(): Promise<Array<Assignment>>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllBillingRecords(): Promise<Array<BillingRecord>>;
    getAllClaims(): Promise<Array<Claim>>;
    getAllDynamicRules(): Promise<Array<DynamicEligibilityRule>>;
    getAllEligibilityRules(): Promise<Array<EligibilityRule>>;
    getAllEmployers(): Promise<Array<Employer>>;
    getAllEnrollments(): Promise<Array<Enrollment>>;
    getAllEoiRequests(): Promise<Array<EoiRequest>>;
    getAllMembers(): Promise<Array<Member>>;
    getAllPlans(): Promise<Array<InsurancePlan>>;
    getAssignmentsByRole(role: AssignmentRole): Promise<Array<Assignment>>;
    getBillingRecordsByMember(memberId: MemberId): Promise<Array<BillingRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClaimsByMember(memberId: MemberId): Promise<Array<Claim>>;
    getDynamicRulesByPlan(planId: bigint): Promise<Array<DynamicEligibilityRule>>;
    getEligibilityRule(id: bigint): Promise<EligibilityRule | null>;
    getEmployer(id: EmployerId): Promise<Employer | null>;
    getEnrollmentsByMember(memberId: MemberId): Promise<Array<Enrollment>>;
    getEoiRequestsByStatus(status: EoiStatus): Promise<Array<EoiRequest>>;
    getMember(id: MemberId): Promise<Member | null>;
    getMembersByEmployer(employerId: EmployerId): Promise<Array<Member>>;
    getPlan(id: PlanId): Promise<InsurancePlan | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seed(): Promise<void>;
    updateAssignment(id: AssignmentId, assignment: Assignment): Promise<void>;
    updateBillingRecord(id: BillingRecordId, record: BillingRecord): Promise<void>;
    updateClaim(id: ClaimId, claim: Claim): Promise<void>;
    updateDynamicRule(id: bigint, rule: DynamicEligibilityRule): Promise<void>;
    updateEligibilityRule(id: bigint, rule: EligibilityRule): Promise<void>;
    updateEmployer(id: EmployerId, employer: Employer): Promise<void>;
    updateEoiStatus(id: EoiRequestId, status: EoiStatus, by: string, atText: string, note: string): Promise<void>;
    updateMember(id: MemberId, member: Member): Promise<void>;
    updatePlan(id: PlanId, plan: InsurancePlan): Promise<void>;
    validateClaim(memberId: MemberId, enrollmentId: EnrollmentId): Promise<[boolean, number]>;
}
import type { Assignment as _Assignment, AssignmentId as _AssignmentId, AssignmentRole as _AssignmentRole, AssignmentStatus as _AssignmentStatus, AuditEntry as _AuditEntry, BillingRecord as _BillingRecord, BillingRecordId as _BillingRecordId, BillingStatus as _BillingStatus, BillingType as _BillingType, Claim as _Claim, ClaimId as _ClaimId, ClaimStatus as _ClaimStatus, CoverageType as _CoverageType, EligibilityEvalResult as _EligibilityEvalResult, EligibilityRule as _EligibilityRule, Employer as _Employer, EmployerId as _EmployerId, EmployerStatus as _EmployerStatus, EmploymentType as _EmploymentType, Enrollment as _Enrollment, EnrollmentId as _EnrollmentId, EnrollmentStatus as _EnrollmentStatus, EoiRequest as _EoiRequest, EoiRequestId as _EoiRequestId, EoiStatus as _EoiStatus, InsurancePlan as _InsurancePlan, Member as _Member, MemberId as _MemberId, MemberStatus as _MemberStatus, PlanId as _PlanId, PlanStatus as _PlanStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignEoiRequest(arg0: EoiRequestId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignEoiRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignEoiRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async checkEligibility(arg0: MemberId, arg1: PlanId): Promise<EligibilityCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEligibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEligibility(arg0, arg1);
            return result;
        }
    }
    async createAssignment(arg0: string, arg1: string, arg2: AssignmentRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, to_candid_AssignmentRole_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, to_candid_AssignmentRole_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createBillingRecord(arg0: EnrollmentId, arg1: MemberId, arg2: BillingType, arg3: string, arg4: number, arg5: number, arg6: number, arg7: string, arg8: string): Promise<BillingRecordId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBillingRecord(arg0, arg1, to_candid_BillingType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBillingRecord(arg0, arg1, to_candid_BillingType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createClaim(arg0: MemberId, arg1: EnrollmentId, arg2: string, arg3: number, arg4: ClaimStatus, arg5: boolean, arg6: number): Promise<ClaimId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, to_candid_ClaimStatus_n7(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, to_candid_ClaimStatus_n7(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createDynamicRule(arg0: DynamicEligibilityRule): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDynamicRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDynamicRule(arg0);
            return result;
        }
    }
    async createEligibilityRule(arg0: EligibilityRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEligibilityRule(to_candid_EligibilityRule_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEligibilityRule(to_candid_EligibilityRule_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEmployer(arg0: string, arg1: string, arg2: string): Promise<EmployerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployer(arg0, arg1, arg2);
            return result;
        }
    }
    async createEoiRequest(arg0: EnrollmentId, arg1: MemberId, arg2: PlanId, arg3: number, arg4: number, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEoiRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEoiRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createMember(arg0: Member): Promise<MemberId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(to_candid_Member_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(to_candid_Member_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPlan(arg0: InsurancePlan): Promise<PlanId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlan(to_candid_InsurancePlan_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlan(to_candid_InsurancePlan_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAssignment(arg0: AssignmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async deleteDynamicRule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDynamicRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDynamicRule(arg0);
            return result;
        }
    }
    async deleteEligibilityRule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEligibilityRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEligibilityRule(arg0);
            return result;
        }
    }
    async deleteEmployer(arg0: EmployerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployer(arg0);
            return result;
        }
    }
    async deleteMember(arg0: MemberId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deletePlan(arg0: PlanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0);
            return result;
        }
    }
    async enrollMember(arg0: MemberId, arg1: PlanId, arg2: number, arg3: string): Promise<EnrollmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollMember(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollMember(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async evaluateMemberEligibility(arg0: bigint, arg1: bigint): Promise<EligibilityEvalResult> {
        if (this.processError) {
            try {
                const result = await this.actor.evaluateMemberEligibility(arg0, arg1);
                return from_candid_EligibilityEvalResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.evaluateMemberEligibility(arg0, arg1);
            return from_candid_EligibilityEvalResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAssignments();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAssignments();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBillingRecords(): Promise<Array<BillingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBillingRecords();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBillingRecords();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClaims(): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClaims();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClaims();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDynamicRules(): Promise<Array<DynamicEligibilityRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDynamicRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDynamicRules();
            return result;
        }
    }
    async getAllEligibilityRules(): Promise<Array<EligibilityRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEligibilityRules();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEligibilityRules();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployers(): Promise<Array<Employer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployers();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployers();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnrollments(): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnrollments();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnrollments();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEoiRequests(): Promise<Array<EoiRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEoiRequests();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEoiRequests();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlans(): Promise<Array<InsurancePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignmentsByRole(arg0: AssignmentRole): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsByRole(to_candid_AssignmentRole_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsByRole(to_candid_AssignmentRole_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillingRecordsByMember(arg0: MemberId): Promise<Array<BillingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingRecordsByMember(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingRecordsByMember(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaimsByMember(arg0: MemberId): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByMember(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByMember(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDynamicRulesByPlan(arg0: bigint): Promise<Array<DynamicEligibilityRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDynamicRulesByPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDynamicRulesByPlan(arg0);
            return result;
        }
    }
    async getEligibilityRule(arg0: bigint): Promise<EligibilityRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEligibilityRule(arg0);
                return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEligibilityRule(arg0);
            return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployer(arg0: EmployerId): Promise<Employer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployer(arg0);
                return from_candid_opt_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployer(arg0);
            return from_candid_opt_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnrollmentsByMember(arg0: MemberId): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentsByMember(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentsByMember(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEoiRequestsByStatus(arg0: EoiStatus): Promise<Array<EoiRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEoiRequestsByStatus(to_candid_EoiStatus_n84(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEoiRequestsByStatus(to_candid_EoiStatus_n84(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: MemberId): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembersByEmployer(arg0: EmployerId): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersByEmployer(arg0);
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersByEmployer(arg0);
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlan(arg0: PlanId): Promise<InsurancePlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlan(arg0);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlan(arg0);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seed();
            return result;
        }
    }
    async updateAssignment(arg0: AssignmentId, arg1: Assignment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignment(arg0, to_candid_Assignment_n88(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignment(arg0, to_candid_Assignment_n88(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBillingRecord(arg0: BillingRecordId, arg1: BillingRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillingRecord(arg0, to_candid_BillingRecord_n91(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillingRecord(arg0, to_candid_BillingRecord_n91(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClaim(arg0: ClaimId, arg1: Claim): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClaim(arg0, to_candid_Claim_n95(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClaim(arg0, to_candid_Claim_n95(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDynamicRule(arg0: bigint, arg1: DynamicEligibilityRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDynamicRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDynamicRule(arg0, arg1);
            return result;
        }
    }
    async updateEligibilityRule(arg0: bigint, arg1: EligibilityRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEligibilityRule(arg0, to_candid_EligibilityRule_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEligibilityRule(arg0, to_candid_EligibilityRule_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployer(arg0: EmployerId, arg1: Employer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployer(arg0, to_candid_Employer_n97(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployer(arg0, to_candid_Employer_n97(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEoiStatus(arg0: EoiRequestId, arg1: EoiStatus, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEoiStatus(arg0, to_candid_EoiStatus_n84(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEoiStatus(arg0, to_candid_EoiStatus_n84(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async updateMember(arg0: MemberId, arg1: Member): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, to_candid_Member_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, to_candid_Member_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlan(arg0: PlanId, arg1: InsurancePlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlan(arg0, to_candid_InsurancePlan_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlan(arg0, to_candid_InsurancePlan_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateClaim(arg0: MemberId, arg1: EnrollmentId): Promise<[boolean, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.validateClaim(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateClaim(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
}
function from_candid_AssignmentRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentRole): AssignmentRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AssignmentStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentStatus): AssignmentStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_BillingRecord_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingRecord): BillingRecord {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_BillingStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingStatus): BillingStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_BillingType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingType): BillingType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimStatus): ClaimStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Claim_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Claim): Claim {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_CoverageType_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoverageType): CoverageType {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid_EligibilityEvalResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EligibilityEvalResult): EligibilityEvalResult {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_EligibilityRule_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EligibilityRule): EligibilityRule {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_EmployerStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployerStatus): EmployerStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Employer_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employer): Employer {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollmentStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollmentStatus): EnrollmentStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Enrollment_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enrollment): Enrollment {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_EoiRequest_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EoiRequest): EoiRequest {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_EoiStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EoiStatus): EoiStatus {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_InsurancePlan_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsurancePlan): InsurancePlan {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_MemberStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberStatus): MemberStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_PlanStatus_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanStatus): PlanStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EligibilityRule]): EligibilityRule | null {
    return value.length === 0 ? null : from_candid_EligibilityRule_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employer]): Employer | null {
    return value.length === 0 ? null : from_candid_Employer_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : from_candid_Member_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InsurancePlan]): InsurancePlan | null {
    return value.length === 0 ? null : from_candid_InsurancePlan_n74(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchedRuleId: [] | [bigint];
    eligible: boolean;
    reason: string;
}): {
    matchedRuleId?: bigint;
    eligible: boolean;
    reason: string;
} {
    return {
        matchedRuleId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.matchedRuleId)),
        eligible: value.eligible,
        reason: value.reason
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    status: _AssignmentStatus;
    name: string;
    role: _AssignmentRole;
    email: string;
}): {
    id: AssignmentId;
    status: AssignmentStatus;
    name: string;
    role: AssignmentRole;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_AssignmentStatus_n30(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: from_candid_AssignmentRole_n32(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BillingRecordId;
    status: _BillingStatus;
    memberId: _MemberId;
    enrollmentId: _EnrollmentId;
    premium: number;
    rate: number;
    createdAtText: string;
    invoiceNumber: string;
    billingPeriodText: string;
    coverageAmount: number;
    retroAdjustment: [] | [number];
    billingType: _BillingType;
}): {
    id: BillingRecordId;
    status: BillingStatus;
    memberId: MemberId;
    enrollmentId: EnrollmentId;
    premium: number;
    rate: number;
    createdAtText: string;
    invoiceNumber: string;
    billingPeriodText: string;
    coverageAmount: number;
    retroAdjustment?: number;
    billingType: BillingType;
} {
    return {
        id: value.id,
        status: from_candid_BillingStatus_n37(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        enrollmentId: value.enrollmentId,
        premium: value.premium,
        rate: value.rate,
        createdAtText: value.createdAtText,
        invoiceNumber: value.invoiceNumber,
        billingPeriodText: value.billingPeriodText,
        coverageAmount: value.coverageAmount,
        retroAdjustment: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.retroAdjustment)),
        billingType: from_candid_BillingType_n40(_uploadFile, _downloadFile, value.billingType)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClaimId;
    status: _ClaimStatus;
    memberId: _MemberId;
    claimAmount: number;
    enrollmentId: _EnrollmentId;
    coverageValid: boolean;
    coverageAmount: number;
    dateOfLossText: string;
}): {
    id: ClaimId;
    status: ClaimStatus;
    memberId: MemberId;
    claimAmount: number;
    enrollmentId: EnrollmentId;
    coverageValid: boolean;
    coverageAmount: number;
    dateOfLossText: string;
} {
    return {
        id: value.id,
        status: from_candid_ClaimStatus_n45(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        claimAmount: value.claimAmount,
        enrollmentId: value.enrollmentId,
        coverageValid: value.coverageValid,
        coverageAmount: value.coverageAmount,
        dateOfLossText: value.dateOfLossText
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    planId: _PlanId;
    waitingPeriodDays: bigint;
    allowedEmploymentTypes: Array<_EmploymentType>;
}): {
    id: bigint;
    active: boolean;
    planId: PlanId;
    waitingPeriodDays: bigint;
    allowedEmploymentTypes: Array<EmploymentType>;
} {
    return {
        id: value.id,
        active: value.active,
        planId: value.planId,
        waitingPeriodDays: value.waitingPeriodDays,
        allowedEmploymentTypes: from_candid_vec_n50(_uploadFile, _downloadFile, value.allowedEmploymentTypes)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployerId;
    status: _EmployerStatus;
    name: string;
    contactEmail: string;
    industry: string;
}): {
    id: EmployerId;
    status: EmployerStatus;
    name: string;
    contactEmail: string;
    industry: string;
} {
    return {
        id: value.id,
        status: from_candid_EmployerStatus_n56(_uploadFile, _downloadFile, value.status),
        name: value.name,
        contactEmail: value.contactEmail,
        industry: value.industry
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EnrollmentId;
    status: _EnrollmentStatus;
    memberId: _MemberId;
    enrollmentDateText: string;
    eoiTriggered: boolean;
    planId: _PlanId;
    coverageAmount: number;
}): {
    id: EnrollmentId;
    status: EnrollmentStatus;
    memberId: MemberId;
    enrollmentDateText: string;
    eoiTriggered: boolean;
    planId: PlanId;
    coverageAmount: number;
} {
    return {
        id: value.id,
        status: from_candid_EnrollmentStatus_n60(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        enrollmentDateText: value.enrollmentDateText,
        eoiTriggered: value.eoiTriggered,
        planId: value.planId,
        coverageAmount: value.coverageAmount
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EoiRequestId;
    status: _EoiStatus;
    memberId: _MemberId;
    enrollmentId: _EnrollmentId;
    assignedTo: [] | [string];
    planId: _PlanId;
    auditLog: Array<_AuditEntry>;
    slaDeadlineText: string;
    giLimit: number;
    coverageRequested: number;
    submittedAtText: string;
}): {
    id: EoiRequestId;
    status: EoiStatus;
    memberId: MemberId;
    enrollmentId: EnrollmentId;
    assignedTo?: string;
    planId: PlanId;
    auditLog: Array<AuditEntry>;
    slaDeadlineText: string;
    giLimit: number;
    coverageRequested: number;
    submittedAtText: string;
} {
    return {
        id: value.id,
        status: from_candid_EoiStatus_n65(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        enrollmentId: value.enrollmentId,
        assignedTo: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.assignedTo)),
        planId: value.planId,
        auditLog: value.auditLog,
        slaDeadlineText: value.slaDeadlineText,
        giLimit: value.giLimit,
        coverageRequested: value.coverageRequested,
        submittedAtText: value.submittedAtText
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    status: _MemberStatus;
    salary: number;
    hireDateText: string;
    email: string;
    employmentType: _EmploymentType;
    employerId: _EmployerId;
    lastName: string;
    firstName: string;
}): {
    id: MemberId;
    status: MemberStatus;
    salary: number;
    hireDateText: string;
    email: string;
    employmentType: EmploymentType;
    employerId: EmployerId;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        status: from_candid_MemberStatus_n71(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        hireDateText: value.hireDateText,
        email: value.email,
        employmentType: from_candid_EmploymentType_n51(_uploadFile, _downloadFile, value.employmentType),
        employerId: value.employerId,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlanId;
    status: _PlanStatus;
    coverageValue: number;
    name: string;
    effectiveDateText: string;
    version: bigint;
    giLimit: number;
    coverageType: _CoverageType;
}): {
    id: PlanId;
    status: PlanStatus;
    coverageValue: number;
    name: string;
    effectiveDateText: string;
    version: bigint;
    giLimit: number;
    coverageType: CoverageType;
} {
    return {
        id: value.id,
        status: from_candid_PlanStatus_n76(_uploadFile, _downloadFile, value.status),
        coverageValue: value.coverageValue,
        name: value.name,
        effectiveDateText: value.effectiveDateText,
        version: value.version,
        giLimit: value.giLimit,
        coverageType: from_candid_CoverageType_n77(_uploadFile, _downloadFile, value.coverageType)
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): EmployerStatus {
    return "active" in value ? EmployerStatus.active : "inactive" in value ? EmployerStatus.inactive : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    billing: null;
} | {
    underwriter: null;
} | {
    viewer: null;
}): AssignmentRole {
    return "admin" in value ? AssignmentRole.admin : "billing" in value ? AssignmentRole.billing : "underwriter" in value ? AssignmentRole.underwriter : "viewer" in value ? AssignmentRole.viewer : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    issued: null;
} | {
    draft: null;
}): BillingStatus {
    return "paid" in value ? BillingStatus.paid : "issued" in value ? BillingStatus.issued : "draft" in value ? BillingStatus.draft : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    list: null;
} | {
    self: null;
} | {
    retro: null;
}): BillingType {
    return "list" in value ? BillingType.list : "self" in value ? BillingType.self : "retro" in value ? BillingType.retro : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    validated: null;
} | {
    denied: null;
} | {
    approved: null;
}): ClaimStatus {
    return "submitted" in value ? ClaimStatus.submitted : "validated" in value ? ClaimStatus.validated : "denied" in value ? ClaimStatus.denied : "approved" in value ? ClaimStatus.approved : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    part_time: null;
} | {
    full_time: null;
}): EmploymentType {
    return "contract" in value ? EmploymentType.contract : "part_time" in value ? EmploymentType.part_time : "full_time" in value ? EmploymentType.full_time : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
} | {
    eoi_pending: null;
}): EnrollmentStatus {
    return "active" in value ? EnrollmentStatus.active : "terminated" in value ? EnrollmentStatus.terminated : "eoi_pending" in value ? EnrollmentStatus.eoi_pending : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    in_review: null;
} | {
    approved: null;
} | {
    declined: null;
}): EoiStatus {
    return "pending" in value ? EoiStatus.pending : "in_review" in value ? EoiStatus.in_review : "approved" in value ? EoiStatus.approved : "declined" in value ? EoiStatus.declined : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
}): MemberStatus {
    return "active" in value ? MemberStatus.active : "terminated" in value ? MemberStatus.terminated : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salary_multiple: null;
} | {
    flat: null;
}): CoverageType {
    return "salary_multiple" in value ? CoverageType.salary_multiple : "flat" in value ? CoverageType.flat : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillingRecord>): Array<BillingRecord> {
    return value.map((x)=>from_candid_BillingRecord_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Claim>): Array<Claim> {
    return value.map((x)=>from_candid_Claim_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EligibilityRule>): Array<EligibilityRule> {
    return value.map((x)=>from_candid_EligibilityRule_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmploymentType>): Array<EmploymentType> {
    return value.map((x)=>from_candid_EmploymentType_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employer>): Array<Employer> {
    return value.map((x)=>from_candid_Employer_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enrollment>): Array<Enrollment> {
    return value.map((x)=>from_candid_Enrollment_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EoiRequest>): Array<EoiRequest> {
    return value.map((x)=>from_candid_EoiRequest_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsurancePlan>): Array<InsurancePlan> {
    return value.map((x)=>from_candid_InsurancePlan_n74(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentRole): _AssignmentRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AssignmentStatus_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentStatus): _AssignmentStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Assignment_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Assignment): _Assignment {
    return to_candid_record_n89(_uploadFile, _downloadFile, value);
}
function to_candid_BillingRecord_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingRecord): _BillingRecord {
    return to_candid_record_n92(_uploadFile, _downloadFile, value);
}
function to_candid_BillingStatus_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingStatus): _BillingStatus {
    return to_candid_variant_n94(_uploadFile, _downloadFile, value);
}
function to_candid_BillingType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingType): _BillingType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ClaimStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClaimStatus): _ClaimStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Claim_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Claim): _Claim {
    return to_candid_record_n96(_uploadFile, _downloadFile, value);
}
function to_candid_CoverageType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoverageType): _CoverageType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_EligibilityRule_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EligibilityRule): _EligibilityRule {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_EmployerStatus_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployerStatus): _EmployerStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Employer_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employer): _Employer {
    return to_candid_record_n98(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_EoiStatus_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EoiStatus): _EoiStatus {
    return to_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function to_candid_InsurancePlan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsurancePlan): _InsurancePlan {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_MemberStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Member_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): _Member {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PlanStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStatus): _PlanStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    planId: PlanId;
    waitingPeriodDays: bigint;
    allowedEmploymentTypes: Array<EmploymentType>;
}): {
    id: bigint;
    active: boolean;
    planId: _PlanId;
    waitingPeriodDays: bigint;
    allowedEmploymentTypes: Array<_EmploymentType>;
} {
    return {
        id: value.id,
        active: value.active,
        planId: value.planId,
        waitingPeriodDays: value.waitingPeriodDays,
        allowedEmploymentTypes: to_candid_vec_n11(_uploadFile, _downloadFile, value.allowedEmploymentTypes)
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MemberId;
    status: MemberStatus;
    salary: number;
    hireDateText: string;
    email: string;
    employmentType: EmploymentType;
    employerId: EmployerId;
    lastName: string;
    firstName: string;
}): {
    id: _MemberId;
    status: _MemberStatus;
    salary: number;
    hireDateText: string;
    email: string;
    employmentType: _EmploymentType;
    employerId: _EmployerId;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        status: to_candid_MemberStatus_n16(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        hireDateText: value.hireDateText,
        email: value.email,
        employmentType: to_candid_EmploymentType_n12(_uploadFile, _downloadFile, value.employmentType),
        employerId: value.employerId,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PlanId;
    status: PlanStatus;
    coverageValue: number;
    name: string;
    effectiveDateText: string;
    version: bigint;
    giLimit: number;
    coverageType: CoverageType;
}): {
    id: _PlanId;
    status: _PlanStatus;
    coverageValue: number;
    name: string;
    effectiveDateText: string;
    version: bigint;
    giLimit: number;
    coverageType: _CoverageType;
} {
    return {
        id: value.id,
        status: to_candid_PlanStatus_n20(_uploadFile, _downloadFile, value.status),
        coverageValue: value.coverageValue,
        name: value.name,
        effectiveDateText: value.effectiveDateText,
        version: value.version,
        giLimit: value.giLimit,
        coverageType: to_candid_CoverageType_n22(_uploadFile, _downloadFile, value.coverageType)
    };
}
function to_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AssignmentId;
    status: AssignmentStatus;
    name: string;
    role: AssignmentRole;
    email: string;
}): {
    id: _AssignmentId;
    status: _AssignmentStatus;
    name: string;
    role: _AssignmentRole;
    email: string;
} {
    return {
        id: value.id,
        status: to_candid_AssignmentStatus_n90(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: to_candid_AssignmentRole_n3(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: BillingRecordId;
    status: BillingStatus;
    memberId: MemberId;
    enrollmentId: EnrollmentId;
    premium: number;
    rate: number;
    createdAtText: string;
    invoiceNumber: string;
    billingPeriodText: string;
    coverageAmount: number;
    retroAdjustment?: number;
    billingType: BillingType;
}): {
    id: _BillingRecordId;
    status: _BillingStatus;
    memberId: _MemberId;
    enrollmentId: _EnrollmentId;
    premium: number;
    rate: number;
    createdAtText: string;
    invoiceNumber: string;
    billingPeriodText: string;
    coverageAmount: number;
    retroAdjustment: [] | [number];
    billingType: _BillingType;
} {
    return {
        id: value.id,
        status: to_candid_BillingStatus_n93(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        enrollmentId: value.enrollmentId,
        premium: value.premium,
        rate: value.rate,
        createdAtText: value.createdAtText,
        invoiceNumber: value.invoiceNumber,
        billingPeriodText: value.billingPeriodText,
        coverageAmount: value.coverageAmount,
        retroAdjustment: value.retroAdjustment ? candid_some(value.retroAdjustment) : candid_none(),
        billingType: to_candid_BillingType_n5(_uploadFile, _downloadFile, value.billingType)
    };
}
function to_candid_record_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ClaimId;
    status: ClaimStatus;
    memberId: MemberId;
    claimAmount: number;
    enrollmentId: EnrollmentId;
    coverageValid: boolean;
    coverageAmount: number;
    dateOfLossText: string;
}): {
    id: _ClaimId;
    status: _ClaimStatus;
    memberId: _MemberId;
    claimAmount: number;
    enrollmentId: _EnrollmentId;
    coverageValid: boolean;
    coverageAmount: number;
    dateOfLossText: string;
} {
    return {
        id: value.id,
        status: to_candid_ClaimStatus_n7(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        claimAmount: value.claimAmount,
        enrollmentId: value.enrollmentId,
        coverageValid: value.coverageValid,
        coverageAmount: value.coverageAmount,
        dateOfLossText: value.dateOfLossText
    };
}
function to_candid_record_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EmployerId;
    status: EmployerStatus;
    name: string;
    contactEmail: string;
    industry: string;
}): {
    id: _EmployerId;
    status: _EmployerStatus;
    name: string;
    contactEmail: string;
    industry: string;
} {
    return {
        id: value.id,
        status: to_candid_EmployerStatus_n99(_uploadFile, _downloadFile, value.status),
        name: value.name,
        contactEmail: value.contactEmail,
        industry: value.industry
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    contract: null;
} | {
    part_time: null;
} | {
    full_time: null;
} {
    return value == EmploymentType.contract ? {
        contract: null
    } : value == EmploymentType.part_time ? {
        part_time: null
    } : value == EmploymentType.full_time ? {
        full_time: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    active: null;
} | {
    terminated: null;
} {
    return value == MemberStatus.active ? {
        active: null
    } : value == MemberStatus.terminated ? {
        terminated: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployerStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == EmployerStatus.active ? {
        active: null
    } : value == EmployerStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoverageType): {
    salary_multiple: null;
} | {
    flat: null;
} {
    return value == CoverageType.salary_multiple ? {
        salary_multiple: null
    } : value == CoverageType.flat ? {
        flat: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentRole): {
    admin: null;
} | {
    billing: null;
} | {
    underwriter: null;
} | {
    viewer: null;
} {
    return value == AssignmentRole.admin ? {
        admin: null
    } : value == AssignmentRole.billing ? {
        billing: null
    } : value == AssignmentRole.underwriter ? {
        underwriter: null
    } : value == AssignmentRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingType): {
    list: null;
} | {
    self: null;
} | {
    retro: null;
} {
    return value == BillingType.list ? {
        list: null
    } : value == BillingType.self ? {
        self: null
    } : value == BillingType.retro ? {
        retro: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClaimStatus): {
    submitted: null;
} | {
    validated: null;
} | {
    denied: null;
} | {
    approved: null;
} {
    return value == ClaimStatus.submitted ? {
        submitted: null
    } : value == ClaimStatus.validated ? {
        validated: null
    } : value == ClaimStatus.denied ? {
        denied: null
    } : value == ClaimStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EoiStatus): {
    pending: null;
} | {
    in_review: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == EoiStatus.pending ? {
        pending: null
    } : value == EoiStatus.in_review ? {
        in_review: null
    } : value == EoiStatus.approved ? {
        approved: null
    } : value == EoiStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingStatus): {
    paid: null;
} | {
    issued: null;
} | {
    draft: null;
} {
    return value == BillingStatus.paid ? {
        paid: null
    } : value == BillingStatus.issued ? {
        issued: null
    } : value == BillingStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmploymentType>): Array<_EmploymentType> {
    return value.map((x)=>to_candid_EmploymentType_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
